name: Export Notebook

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Generate Notebook PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r compilation/requirements.txt
          python -m playwright install --with-deps chromium

      - name: Export notebook
        run: python compilation/export_notebook.py

      - name: Upload notebook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: team-5840c-notebook
          path: |
            compilation/output/notebook.html
            compilation/output/notebook.pdf
